import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
const port=8798;const base='http://127.0.0.1:'+port;let child;
before(async()=>{child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),MODEL_API_KEY:'',MODEL_NAME:'',MODEL_API_URL:''},stdio:'ignore'});for(let i=0;i<50;i++){try{if((await fetch(base+'/api/status')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Server did not start');});
after(()=>child?.kill());
test('GET root serves offline bundled application',async()=>{const r=await fetch(base);assert.equal(r.status,200);assert.match(await r.text(),/SOURCE_COUNTS/);});
test('GET source serves native module development shell',async()=>{const r=await fetch(base+'/source');assert.equal(r.status,200);assert.match(await r.text(),/styles-v2.css/);});
test('status does not expose credentials',async()=>{const r=await(await fetch(base+'/api/status')).json();assert.equal(r.configured,false);assert.equal(r.privateNotesUploaded,false);});
test('knowledge audit endpoint reports actual totals',async()=>{const r=await(await fetch(base+'/api/knowledge')).json();assert.equal(r.ok,true);assert.equal(r.sources,36);assert.equal(r.questions,24);});
test('source endpoint filters eight Zhihu agent entries',async()=>{const r=await(await fetch(base+'/api/sources?topic=ai-agents&kind=zhihu')).json();assert.equal(r.items.length,8);assert.ok(r.items.every(x=>x.access==='index-only'));});
test('query API performs actual local retrieval',async()=>{const r=await(await fetch(base+'/api/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:'Agent workflow',topic:'ai-agents'})})).json();assert.equal(r.ok,true);assert.ok(r.sources.length>=1);});
test('no matching query returns explicit insufficiency',async()=>{const r=await(await fetch(base+'/api/query',{method:'POST',body:JSON.stringify({question:'zzzqxjv991'})})).json();assert.equal(r.ok,false);});
test('invalid JSON query is rejected',async()=>{const r=await fetch(base+'/api/query',{method:'POST',body:'not-json'});assert.equal(r.status,400);});
test('unconfigured model never fabricates success',async()=>{const r=await fetch(base+'/api/generate',{method:'POST',body:JSON.stringify({topic:'example'})});assert.equal(r.status,503);});
test('private env cannot be downloaded',async()=>{const r=await fetch(base+'/.env');assert.equal(r.status,404);});
test('unknown API is a 404',async()=>{assert.equal((await fetch(base+'/api/unknown')).status,404);});
test('script is returned with correct content type',async()=>{const r=await fetch(base+'/src/activity-engine.mjs');assert.match(r.headers.get('content-type'),/javascript/);});
test('HEAD returns no HTML body',async()=>{const r=await fetch(base,{method:'HEAD'});assert.equal(r.status,200);assert.equal(await r.text(),'');});
test('unsupported static write method is rejected',async()=>{assert.equal((await fetch(base,{method:'POST'})).status,405);});
